{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.redirectHTTP }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "cmdb-frontend.fullname" . }}-https-redirect
  labels:
    {{- include "cmdb-frontend.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
