{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "cmdb-frontend.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "cmdb-frontend.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
